# Generated by Django 5.2.5 on 2025-08-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0002_login_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_Tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='pictures')),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
