# Generated by Django 5.2.5 on 2025-08-27 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0003_product_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_Tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('fname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec.reg_tbl')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec.product_tbl')),
            ],
        ),
    ]
