# Generated by Django 5.2.5 on 2025-08-29 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0004_cart_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_Tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec.reg_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='orderItem_Tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='ec.order_tbl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec.product_tbl')),
            ],
        ),
    ]
